### ISSUE TITLE
看视频频繁报错 扩展版本为1.0.6

### ISSUE THREAD

**Issue by qjzcj2008** [esterTion/Youku-HTML5-Player#1]
报错信息为
播放错误
{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 404,
    "msg": "Not Found"
  }
}

**Comment by esterTion** [comment]
页面地址

**Comment by qjzcj2008** [comment]
不只在一个视频出现该问题，今晚我在追人民的名义，连续5集都出现了这个问题，每一个视频出现的位置均不固定

**Comment by esterTion** [comment]
还是具体给我个地址和大概时间，这样方便我排错
先确认是不是代码问题之类的
怀疑接口数据可能有问题

**Comment by esterTion** [comment]
已更新1.0.7
