### ISSUE TITLE
外链播放没有替换

### ISSUE THREAD

**Issue by zhanxiage233** [esterTion/Youku-HTML5-Player#100]
http://www.3dmgame.com/news/201709/3690488.html

**Comment by zanewayne78** [comment]
还没修复么

**Comment by VCHECKZEN** [comment]
http://doyoudo.com/
这个网站的外链也没有替换，之前优酷没有使用html5播放器的时候是可以替换的，现在优酷启用了html5播放器，是不是替换逻辑需要更改一下，忘作者抽时间看一下

**Comment by esterTion** [comment]
已更新1.3.1.8
