### ISSUE TITLE
火狐上打开一个视频，h5和flash是不是在同时播放啊？？？

### ISSUE THREAD

**Issue by marshall4484** [esterTion/Youku-HTML5-Player#103]
一个视频播放2个声音不同步，暂停前台后台声音还在播，是不是h5和flash在同时播放呢？？？

**Comment by esterTion** [comment]
火狐版本？
扩展版本？

**Comment by marshall4484** [comment]
挺怪的，之前火狐扩展版本有时候是运行扩展的h5播放器有时候又变成运行官方的h5播放器，今天又移除重新安装了一次，同时有2个声音在播放的问题还在，但刷新几次就能搞定这个问题。
另外，如果刷新几次扩展正常工作uncaught exception: Violent break就有，如果没有正常工作uncaught exception: Violent break这个就没有！

**Comment by esterTion** [comment]
浏览器版本？
火狐是比较可能导致中断官方播放器的代码执行晚于播放器创建，这样就会出问题

**Comment by marshall4484** [comment]
火狐版本是55.0.3
扩展版本是1.3.1.9

**Comment by marshall4484** [comment]
火狐版本是55.0.3
扩展版本是1.3.1.9

**Comment by marshall4484** [comment]
我刚刚把flash插件禁用，视频还是出现了两个声音，是不是另外还加载了官方的h5播放器呢

**Comment by xinggsf** [comment]
这不是提问的态度，网址、截图、控制台信息都未给出！
若是我，就懒得理会

**Comment by waldens** [comment]
@esterTion 同遇到这问题

### 现象
观看优酷视频时，有前、后台，2个声音同时播放（后台声音，有时是当前视频的，有时是广告的，取决于是否用ublock屏蔽广告）。点击画面暂停前台以后，后台声音仍在继续播放

### 环境
Win7x64 & Firefox56.0.1x86 & YAPfY 1.3.2
（之前v1.3.1.x就有该问题，但一直懒得排查+反馈。今天更新1.3.2后，依然有这问题）

### 重现步骤
没发现基于空白profile的、100%必现的重现步骤

### 做过的排查
1. 全新空白profile+仅安装YAPfY  -->  一切正常
2. 我的现有profile，移除（不是禁用）其它全部扩展，仅留下YAPfY启用   --> 一切正常
3. 我的现有profile，移除其它全部扩展，只留下YAPfY和GreaseMonkey，但是**GM处于禁用** 状态  --> 两个声音

其实还可以排查下去，比如一个个油猴脚本安装测试，但这就太耗费时间了……我没耐心测下去了

console里没有`uncaught exception: Violent break`

**Comment by esterTion** [comment]
@waldens
谢谢这么详细的实验
再确认一下，在两个声音出现的页面里，在控制台执行一下`$.extend`，看一下返回的函数的名字是$.extend还是p.fn.extend

**Comment by waldens** [comment]
@esterTion 返回function $.extend()
我想上传个测试profile，方便排查，但实在没办法稳定必现。总是有时正常，有时俩声音

**Comment by esterTion** [comment]
尝试了下复现我这边还是没有出现……
留下了禁用的GM还是可以正常中断官方的播放器加载
我之后还是尝试找找有没有其他地方可以更稳妥的中断官方播放器
