### ISSUE TITLE
替换外链播放器的自动全屏

### ISSUE THREAD

**Issue by jiangqingg** [esterTion/Youku-HTML5-Player#104]
在自动全屏下，外链播放的时候是在限制大小的div内的网页全屏状态，要全屏需要点击一下退出网页全屏，然后再浏览器全屏，这里可以改进一下。

弹幕的按钮关闭和开启区分度不高，不能友好的提示当前状态是否显示弹幕

bilibili主题时，当关闭弹幕的时候，控制栏下方的弹幕发送框也可以隐藏

**Comment by esterTion** [comment]
隐藏发送框已更新1.3.1.11

**Comment by esterTion** [comment]
已更新1.3.2.1解决外链网页全屏
