### ISSUE TITLE
播放器图标乱码

### ISSUE THREAD

**Issue by developerdong** [esterTion/Youku-HTML5-Player#105]
![image](https://user-images.githubusercontent.com/15864936/31803484-91a4fe8c-b586-11e7-823b-6e2b9ded1046.png)
播放器底部有些图标正常，有些就是乱码。附上我浏览器的版本信息：
![image](https://user-images.githubusercontent.com/15864936/31803573-13eadf74-b587-11e7-83e6-7b76f6cb7b4f.png)

**Comment by esterTion** [comment]
刷新几下，我之后把资源变成内嵌解决一下

**Comment by esterTion** [comment]
已更新1.3.1.11
