### ISSUE TITLE
弹幕数量限制

### ISSUE THREAD

**Issue by billzt** [esterTion/Youku-HTML5-Player#106]
已经在“弹幕屏蔽设定”那里把数量设成了1条，但是还是满屏的弹幕

**Comment by esterTion** [comment]
你理解错了，那个不是设置弹幕密度上限，是允许的刷屏弹幕数量（10s相同内容出现次数）
弹幕密度没有设来着，我之后加一下

**Comment by billzt** [comment]
原来如此！我一直理解得不对。弹幕密度显示还是很重要的功能。希望尽快上线

**Comment by esterTion** [comment]
已更新1.3.1.12

**Comment by billzt** [comment]
发现一个问题：如果本身弹幕密度很高，我设置缩小弹幕密度之后，自己发的弹幕会被隐藏掉。有没有办法能够让自己发的弹幕始终显示？

**Comment by esterTion** [comment]
把这个忘了，下版本修复

**Comment by esterTion** [comment]
已更新1.3.2
