### ISSUE TITLE
bilibili主题全屏时底下有白条

### ISSUE THREAD

**Issue by Tuztris** [esterTion/Youku-HTML5-Player#107]
浏览器: firefox 58.0a1
插件版本: 1.3.1.11
截图如下, 可能需要点开大图才能看得出来
![j d o_3 d99zv2ipqplg8](https://user-images.githubusercontent.com/14080372/31900823-4b224680-b852-11e7-9a86-7b1ff72f3024.png)

**Comment by esterTion** [comment]
已更新1.3.1.12
