### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by jkle112** [esterTion/Youku-HTML5-Player#108]
安装后的扩展,与其它脚本有冲突,如视频网站HTML5集合,monkey-medio，再见FLASH等HTML5切换类。
因该类确实一般，卸载也没有影响，画面质量还是你的扩展更好。
因tudou.com无法播放，提示去优酷看看，结果才放出来，希望支持tudou.com。
因le.com,pptv.com,baofeng.com,bilibili.com,kankan.com,v.6.cn,fun.tv,和iqiyi.com也是常出错，请一并支持，谢谢！
使用的破解VIP会员视频集合，VIP FREE等脚本，有的需要在播放器左上角嵌入一按钮，请支持，谢谢！

**Comment by Tuztris** [comment]
bilibili.com和iqiyi.com不是本身就有html5播放器么

**Comment by jkle112** [comment]
bilibili.com和iqiyi.com安装的HTML5的脚本不是很好,有的可以,有的不好用,测试多个后,就发现这个扩展比脚本好,而且即使出错了,有提示,方便反馈,同时也知道要调整脚本,有时刷新页面就可以正常播放了,所以测试后才决定去掉那些脚本,让这个扩展升级就可以了,运行效率高,不容易出现脚本冲突.
个人观点,不对请指正,谢谢!

**Comment by esterTion** [comment]
没有添加其他支持的计划
参见[README说明](https://github.com/esterTion/Youku-HTML5-Player/blob/master/README.md#%E5%85%B3%E4%BA%8E%E6%9B%B4%E5%90%8D)
