### ISSUE TITLE
2017年11月29日 Firefox提示客户端无权播放

### ISSUE THREAD

**Issue by ruoxiweb** [esterTion/Youku-HTML5-Player#110]
2017年11月29日 Firefox提示客户端无权播放
code -6004
勾选使用官方h5播放器后解决

**Comment by esterTion** [comment]
已更新1.3.2.4

**Comment by xiaozhitongxie** [comment]
您好 能在旧版本的用户界面上推送一下要更新这个插件的提示么？我把您的插件推荐给了好多盆友，我可能无法每个人都通知到/

**Comment by esterTion** [comment]
没有写独立于浏览器更新机制之外的更新功能，一般情况下一天之内浏览器会自己更新

**Comment by weiwei007** [comment]
1.3.2.4 chrome版还是有无效播放问题啊

**Comment by esterTion** [comment]
@weiwei007
https://github.com/esterTion/Youku-HTML5-Player/blob/master/CONTRIBUTING.md

**Comment by weiwei007** [comment]
1.3.24更新后依然错误
获取视频地址出错，详细错误：
{"note":"客户端无权播放,201","code":-6004},只能勾选使用官方h5播放器，才能播放

**Comment by esterTion** [comment]
我让你提供复现地址

**Comment by weiwei007** [comment]
http://v.youku.com/v_show/id_XMzAyMDYwOTc5Ng==.html?spm=a2hww.20027244.m_250036.5~5!2~5~5!4~5~5~A

**Comment by esterTion** [comment]
已更新1.3.2.6
