### ISSUE TITLE
替换的播放器无法播放？

### ISSUE THREAD

**Issue by jerry011235** [esterTion/Youku-HTML5-Player#114]
chorme最新版本，无其他扩展影响
替换的播放器无法播放，一直处于“正在切换”状态，只有勾选“使用官方html5播放器”，才能正常播放。
update：换成标清版本好了。

**Comment by esterTion** [comment]
其他链接是否正常
给我一个地址

**Comment by jerry011235** [comment]
@esterTion 你好，目前情况是 高清及以上 一直处于“正在切换”状态，只有在选项勾选“使用官方html5播放器”，才能正常播放。
标清正常。
http://v.youku.com/v_show/id_XMzAwMTgxOTYwOA==.html

**Comment by esterTion** [comment]
所有吗
我明天看看

**Comment by esterTion** [comment]
顺便浏览器/版本也说一下

**Comment by esterTion** [comment]
已更新1.3.2.9

**Comment by jerry011235** [comment]
非常感谢!
