### ISSUE TITLE
Firefox在非官方播放器模式下与IDM冲突

### ISSUE THREAD

**Issue by ryans233** [esterTion/Youku-HTML5-Player#115]
浏览器版本：Firefox Developer Edition 58b11
扩展版本：YAPfY 1.3.2.9
示例地址：https://v.youku.com/v_show/id_XMzIwMzkyMTUzNg==.html?spm=a2hww.20027244.m_250379.5~5~1~3!2~A
问题详情：同时启用IDM官方扩展（IDM 6.30.2）与YAPfY时，打开任意一个优酷视频，IDM会不停嗅探出视频并弹出添加下载任务的提示框，此时网页无法播放视频，并弹出扩展出错的日志。在扩展设置中启用官方HTML5播放器则无此问题。
扩展日志：

> 播放错误
> {
>   "url": "https://v.youku.com/v_show/id_XMzIwMzkyMTUzNg==.html?spm=a2hww.20027244.m_250379.5~5~1~3!2~A",
>   "playing_quality": "mp4hd3v2",
>   "type": "MediaError",
>   "info": "FormatUnsupported",
>   "detail": {
>     "code": -1,
>     "msg": "Non-FLV, Unsupported media type"
>   }
>  }

**Comment by esterTion** [comment]
在`%appdata%\Mozilla\Firefox\Profiles\[一堆随机字符].profile\extensions`里找一下idm扩展，在这里加个附件，文件/文件夹名是`about:support#extensions-tbody`下对应的ID

**Comment by ryans233** [comment]
[idm_ext_firefox_6.30.2.zip](https://github.com/esterTion/Youku-HTML5-Player/files/1570508/idm_ext_firefox_6.30.2.zip)

**Comment by esterTion** [comment]
我这里测试没出现问题，最多视频右上角有按钮
你开了哪个自动下载的设置？

**Comment by ryans233** [comment]
刚刚发现，在IDM设置 – 文件类型里去除MP4即可正常播放。IDM默认会有这个文件类型，而且Chrome是不会被嗅探出的。

发送自 Windows 10 版邮件应用

发件人: esterTion
发送时间: 2017年12月21日 12:58
收件人: esterTion/Youku-HTML5-Player
抄送: Ryan Wu; Author
主题: Re: [esterTion/Youku-HTML5-Player] Firefox在非官方播放器模式下与IDM冲突 (#115)

我这里测试没出现问题，最多视频右上角有按钮
你开了哪个自动下载的设置？
