### ISSUE TITLE
启用替换外链播放器后，cnbeta.com 无法播放，只能点击跳转到优酷网站

### ISSUE THREAD

**Issue by czmecho** [esterTion/Youku-HTML5-Player#116]
![Xo9oT.png](https://s1.ax1x.com/2017/12/20/Xo9oT.png)

win10 chrome 63 环境下

**Comment by esterTion** [comment]
地址

**Comment by czmecho** [comment]
@esterTion 
比如这个：http://www.cnbeta.com/articles/soft/681933.htm
网站所有内嵌优酷的视频都不能很好地替换。

**Comment by esterTion** [comment]
我这边没遇到什么播放问题
点中间黑条是跳，点周围是播放

**Comment by czmecho** [comment]
@esterTion 好吧，我的错，我一直点中间。😳

**Comment by esterTion** [comment]
我这个设计逻辑也确实可能有问题，不是特别明显
区别就是个左下角链接详情有没有显示链接
