### ISSUE TITLE
There are some mistakes

### ISSUE THREAD

**Issue by Rintim** [esterTion/Youku-HTML5-Player#118]
{ "url": "http://v.youku.com/v_show/id_XODU1MDI4NzEy.html?spm=a2h0k.8191407.0.0&from=s1.8-3-1.1&debug=flv", "playing_quality": "flvhd", "type": "MediaError", "info": "MediaMSEError", "detail": { "code": 9, "msg": "Operation is not supported" } }
What's Wrong?

**Comment by esterTion** [comment]
Did reloading solve the problem? 
The extension works fine for me, on this page. Many times such problem is caused by network unstablity.

**Comment by Rintim** [comment]
well,It's my firefox problem.
thanks
