### ISSUE TITLE
新版优酷界面挂了

### ISSUE THREAD

**Issue by WangJi** [esterTion/Youku-HTML5-Player#119]
优酷更新了界面，好像插件有点问题。
控制台显示这里有点问题，估计是元素被移除了:

`document.querySelector('#fn_download').addEventListener('click', generate_downlink);`

**Comment by WangJi** [comment]
Chrome: ` 63.0.3239.132（正式版本） （64 位）`

插件版本: `1.3.2.10`

**Comment by esterTion** [comment]
更新一下

**Comment by WangJi** [comment]
OK了，没注意到你one hour ago的commit。

**Comment by aunsen** [comment]
感谢修复！

**Comment by laowalter** [comment]
firefox 1.3.3 还是不能用了。

例如 http://v.youku.com/v_show/id_XMzM4ODg3NjA3Mg==.html?spm=a2h0k.8191407.0.0
