### ISSUE TITLE
Solved：MAC firefox 1.3.3 无法加载优酷视频

### ISSUE THREAD

**Issue by laowalter** [esterTion/Youku-HTML5-Player#121]
1.3.3 无法加载优酷视频， 我的环境：Mac HIgh Sierra 10.13.3 Firefox 58.02(64-bit)
另外，我的windows 10 上，Firefox 用1.3.3就是比价完美的。

**Comment by esterTion** [comment]
测试Sierra+Firefox 58.0.2正常，家人电脑不好升级

**Comment by laowalter** [comment]
1.3.4 一切正常！ 谢谢！牛！
