### ISSUE TITLE
播放中要时不时给播放器刷新才才能继续播放下去

### ISSUE THREAD

**Issue by ShimotsukiH** [esterTion/Youku-HTML5-Player#124]
反映bug
播放比较长的视频的时候，经常出现需要刷新页面才能继续缓冲视频。
例如：
http://v.youku.com/v_show/id_XMzQzODc5MTYzMg==.html?spm=a2h0j.11185381.listitem_page1.5~A&f=51548967&from=y1.2-3.4.1

**Comment by esterTion** [comment]
比较难以复现，没办法修
