### ISSUE TITLE
优酷个别视频无效

### ISSUE THREAD

**Issue by 448Lucario** [esterTion/Youku-HTML5-Player#125]
http://v.youku.com/v_show/id_XMjI2NTg3NTg0.html?spm=a2h0k.8191407.0.0&lang=%E5%9B%BD%E8%AF%AD
这个网址的视频无法加载插件，用的火狐57

**Comment by esterTion** [comment]
已更新1.4.0

**Comment by esterTion** [comment]
已更新1.4.0

**Comment by esterTion** [comment]
已更新1.4.0

**Comment by GithubUsername3** [comment]
1.4.0在google chrome 67.0.3377.1（64 位）下，播放http://v.youku.com/v_show/id_XMzQ5MjE2MjkwNA==.html?spm=a2h0j.11185381.listitem_page1.5~A&s=e9e2384d2da04e80b2a0  ，会出错，自动降低清晰度

![youku another](https://user-images.githubusercontent.com/29504818/38122739-8e6f9220-3409-11e8-81db-47bc65000511.png)

**Comment by esterTion** [comment]
视频服务器问题，不关我事

**Comment by GithubUsername3** [comment]
firefox用1.4没有问题，chrome用1.4观看其它视频比如烈火如歌没问题，chrome回退到1.3.4观看图片所示视频没问题

**Comment by 448Lucario** [comment]
感谢作者，修复的好快！

**Comment by esterTion** [comment]
刷新几次后确认是服务器问题，chrome v1.4第一次只出现在超清下，然后刷新问题消失
