### ISSUE TITLE
优酷走代理卡顿

### ISSUE THREAD

**Issue by Jason4774** [esterTion/Youku-HTML5-Player#128]
你好，只启用代理扩展和该扩展，优酷http://v.youku.com/v_show/id_XMzUxNDI2NTkwOA==.html?spm=a2hww.20027244.m_250379.5~5~1~3!7~A
全局走ssr服务器卡顿严重，换成官方播放器重启浏览器才正常，排除法说明是该扩展播放器的原因，可能是什么冲突了，审查元素看见错误数字不断增大。望修复，谢谢。

**Comment by esterTion** [comment]
那…为什么要全局ssr呢
