### ISSUE TITLE
这播放器老想着往下面跑

### ISSUE THREAD

**Issue by AMNOTSR** [esterTion/Youku-HTML5-Player#132]
`播放错误

{
  "url": "http://v.youku.com/v_show/id_XMzU3MDM0NjgyMA==.html?spm=a2hww.20027244.m_250379.5~1~3!4~A&f=51675294",
  "playing_quality": "mp4hd3v2",
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 416,
    "msg": "Requested Range Not Satisfiable"
  }
}`
![360 -19765281](https://user-images.githubusercontent.com/19822145/39404175-2b9eaf72-4bc0-11e8-8a9b-f2dbfa33cefe.jpg)

**Comment by esterTion** [comment]
已更新v1.4.1
