### ISSUE TITLE
如果不勾选 使用官方html5播放器，打开一会标签页就崩溃

### ISSUE THREAD

**Issue by MalcKear** [esterTion/Youku-HTML5-Player#133]
测试链接：http://v.youku.com/v_show/id_XOTMzNzc4NjQ4.html
firefox 59.0.3 64位
win10 64
![_20180506213545](https://user-images.githubusercontent.com/3882135/39674044-9d3fdd82-5178-11e8-92e9-e3a5e38c632e.png)

**Comment by esterTion** [comment]
关掉没问题了吗？
看了下这个是启用了fetch的流式读取，可能导致了内存问题。这个不是旧版遗留，是新版测试功能
火狐下有自己的流式传输模块，chrome里至今流式都是大坑，所以建议不开
