### ISSUE TITLE
好像失效了？

### ISSUE THREAD

**Issue by litianyuhehe** [esterTion/Youku-HTML5-Player#136]
播放错误

{
  "url": "http://v.youku.com/v_show/id_XMzYyMjAxNjA2OA==.html",
  "playing_quality": "mp4sd",
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}
外链还是主站都不行

**Comment by AlexLuya** [comment]
我的也是
