### ISSUE TITLE
从1.4.2开始，主站的播放器加载不出来 

### ISSUE THREAD

**Issue by zhanxiage233** [esterTion/Youku-HTML5-Player#141]
浏览器是火狐 从1.4.2开始，主站的播放器加载不出来 外链播放器倒是可以加载出来 切换成官方播放器都没有问题（已经试过禁用UBO） 
退回到1.4.1测试正常

**Comment by esterTion** [comment]
测试没问题
![qq 20181009150545](https://user-images.githubusercontent.com/7265411/46652144-cf867180-cbd4-11e8-9943-958708ecaa13.png)

**Comment by zhanxiage233** [comment]
你这截图像是chrome啊。。。我用的火狐

**Comment by esterTion** [comment]
又有奇怪问题，我发个新版

**Comment by esterTion** [comment]
我？？？？？
debug就能跑一发布就死，ff什么垃圾

**Comment by esterTion** [comment]
……？？？
我机子1.4.3.1跑不了又改了才行，什么玩意儿
现在1.4.3.2应该是稳定能跑了
