### ISSUE TITLE
今天突然无法播放（firefox 65.0 64bit on windows 10)

### ISSUE THREAD

**Issue by cicite** [esterTion/Youku-HTML5-Player#147]
Playback error
{
  "url": "https://v.youku.com/v_show/id_XMzk0OTc1OTgxNg==.html?spm=a2h0j.11185381.listitem_page1.5!2~A&&s=131b1cefbfbdefbfbd73",
  "playing_quality": "mp4sd",
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "NetworkError when attempting to fetch resource."
  }
}

https://v.youku.com/v_show/id_XMzk0OTc1OTgxNg==.html?spm=a2h0j.11185381.listitem_page1.5!2~A&&s=131b1cefbfbdefbfbd73

**Comment by TodDod** [comment]
Playback error
{
  "url": "https://v.youku.com/v_show/id_XMzg1MTk3MTQzMg==.html?spm=a2hww.11359951.m_26657.5~5~1~3~A",
  "playing_quality": "mp4sd",
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "NetworkError when attempting to fetch resource."
  }
}

**Comment by esterTion** [comment]
已更新1.5.0.4
