### ISSUE TITLE
未来会支持Safari吗？

### ISSUE THREAD

**Issue by evindu** [esterTion/Youku-HTML5-Player#15]
未来会支持Safari吗？——来自Mac用户😂

**Comment by esterTion** [comment]
safari扩展有很大的权限问题，而且分发扩展要$99，用不起

**Comment by zhu327** [comment]
可以不用上市场呀 @esterTion

**Comment by esterTion** [comment]
- safari的扩展，不通过苹果分发的话，每次启动浏览器，手动选择扩展位置，重启加载
- safari扩展我之前试过一次，没有跨域特权，所以整个就不行了（之所以写扩展而不是猴子就是因为全都是跨域访问，而且没一个有权限）
