### ISSUE TITLE
1.5.0.1 无法播放

### ISSUE THREAD

**Issue by cicite** [esterTion/Youku-HTML5-Player#150]
很棒的作品！

Windows 10 环境, Firefox 65.0 64bits, 升级到1.5.0.1之后，还是无法播放。一直停在 “Loading video metada” ，点击播放按钮没有反应。

例如 https://v.youku.com/v_show/id_XNDAwNDIxODg4OA==.html?spm=a2ha1.12523948.m_5295_c_12649.d_05

BTW，选择use official html5 player 就没问题。

**Comment by esterTion** [comment]
已更新1.5.0.4
