### ISSUE TITLE
1.1.3 firefox52.0.2下失效

### ISSUE THREAD

**Issue by gsy111** [esterTion/Youku-HTML5-Player#16]
1.1.3 firefox52.0.2下失效,优酷下是flash播放

**Comment by esterTion** [comment]
可能有问题，先装[旧版](https://github.com/esterTion/Youku-HTML5-Player/blob/8096d023d4f2804317b8d1a52afcf5f1168ea861/signed.xpi?raw=true)然后进扩展详情里关闭自动更新，我中午看看

**Comment by lovehomes** [comment]
我也发现这问题了 1.1.3 firefox52.0.2  确实失效了

**Comment by esterTion** [comment]
已更新1.1.4 1.1.5
