### ISSUE TITLE
处理embed模式的建议

### ISSUE THREAD

**Issue by ivysrono** [esterTion/Youku-HTML5-Player#17]
No Embed Youtube
https://greasyfork.org/zh-CN/scripts/1590-no-embed-youtube

参考这个脚本，变成链接回到主站看吧。

**Comment by esterTion** [comment]
embed换iframe其实就可以了，之后看看

**Comment by esterTion** [comment]
已更新1.1.5

**Comment by ivysrono** [comment]
嵌入的视频建议不要自动播放。
个人习惯自动缓存但不播放。
每个人习惯不一样，主站问题不大，但嵌入视频自动播放很干扰，今天在阅读器里突然出声音了，吓了一大跳。

**Comment by esterTion** [comment]
ok，我之后改一下

**Comment by esterTion** [comment]
已更新1.1.6
