### ISSUE TITLE
1.1.6看优酷变空白了啊

### ISSUE THREAD

**Issue by GoogleGFW** [esterTion/Youku-HTML5-Player#20]
1.1.5.1还没问题，刚才升级到1.1.6看优酷变空白都没图像了
QQ浏览器 9.6.11108.400 (内核 53.0.2785.104)

**Comment by esterTion** [comment]
我靠，浏览器

**Comment by esterTion** [comment]
截图一下f12的报错
国产浏览器不在主要支持范围，视情况兼容

**Comment by GoogleGFW** [comment]
![qq](https://cloud.githubusercontent.com/assets/26985927/26093903/521f6f34-3a4a-11e7-98ac-c0e687592c6a.png)

**Comment by esterTion** [comment]
这里面没有一个是扩展的报错，你禁用看看有没有问题

**Comment by GoogleGFW** [comment]
这就尴尬了，，禁用以后刷新flash播放器出来了不空白了，我再重新启用就正常开启H5了，
不好意思麻烦你了。。。。

**Comment by esterTion** [comment]
你浏览器可能缓存了个有问题的jsˊ_>ˋ
