### ISSUE TITLE
最新版的插件 播放出错 Firefox 52.0.2

### ISSUE THREAD

**Issue by lzwgg** [esterTion/Youku-HTML5-Player#25]
![default](https://cloud.githubusercontent.com/assets/15891269/26271332/fb47cfe0-3d36-11e7-8021-124411dbd8ef.png)

最新版的插件

**Comment by esterTion** [comment]
网络问题，刷新无法解决？

**Comment by lzwgg** [comment]
不好意思，是因为我早上有次选了高清，后来删除重新安装，清除youku的cookie，也是一直进不了超清，刷新也是这个报警，不过刚才打开只有标清的视频，播放是正常的，打开最高是高清的视频，播放也是这个报错。

我的firefox没有安装flash播放器。

**Comment by esterTion** [comment]
那有点奇怪
你按照这个步骤试一下重置设置有没有用：

打开 %appdata%\Mozilla\Firefox\Profiles，把xxxx.default备份一下（压缩或者复制到其他地方），然后删除文件夹里的所有文件（文件夹自身留着），再单独安装这个扩展进优酷看有没有报错

**Comment by lzwgg** [comment]
嗯嗯，好了。
