### ISSUE TITLE
弹幕屏蔽总是出问题

### ISSUE THREAD

**Issue by rainning123** [esterTion/Youku-HTML5-Player#27]
屏蔽弹幕（比如颜色弹幕 底部弹幕）
总是在几分钟之后就失效

或者视频卡住自动重新加载后也会失效 这种情况下还会出现一条弹幕变成两行 
比如原本弹幕是：123
重新加载后会变成：123
                                 123

**Comment by rainning123** [comment]
提问发出后空格没了..
会变成：
123
123

**Comment by esterTion** [comment]
懂说的了，之前碰到过忘了解决了

**Comment by rainning123** [comment]
辛苦了

**Comment by esterTion** [comment]
已更新1.1.10
