### ISSUE TITLE
请问一下全屏下老是弹出鼠标跟进度条是什么情况呢？

### ISSUE THREAD

**Issue by Orient-Ea** [esterTion/Youku-HTML5-Player#28]
360极速浏览器，内核版本号50.0.2661.102。

全屏下看视频鼠标不动会自动隐藏鼠标跟进度条，但用这个插件后鼠标跟进度条会在没移动鼠标的情况下反反复复的隐藏和弹出，已尝试关闭别的插件跟JS，还是这样。

**Comment by Orient-Ea** [comment]
拔掉鼠标后虽然不显示鼠标了，但还是会反复弹出进度条。T_T

**Comment by esterTion** [comment]
更新了1.1.10.2，你试一下有没有解决

**Comment by esterTion** [comment]
惊了，怎么issue都没有状态回报的，到底好没啊

![](https://camo.githubusercontent.com/12df4364284001fd0cc091309393a6467e77a674/68747470733a2f2f657374657274696f6e2e77696e2f77702d636f6e74656e742f75706c6f6164732f323031372f30352f666136306664373866653464356564383136623962396635353062383739626362353863323136322e6a706567)

**Comment by Orient-Ea** [comment]
不好意思，出差了2天，马上测试。

**Comment by Orient-Ea** [comment]
更新1.1.11，已解决，谢谢作者！无数个赞！！！

**Comment by esterTion** [comment]
ok，之后我把更新里的可能去掉
