### ISSUE TITLE
还是弹幕屏蔽问题

### ISSUE THREAD

**Issue by rainning123** [esterTion/Youku-HTML5-Player#29]
在勾选了屏蔽底端弹幕后
进入下一集
弹幕就会出现双重弹幕
影响也不大 有空的话再改改吧

**Comment by esterTion** [comment]
哇，惊了，我都写了换源时清空弹幕了

![](https://estertion.win/wp-content/uploads/2017/05/fa60fd78fe4d5ed816b9b9f550b879bcb58c2162.jpeg)

进入下一集是指点链接换视频吗，理应是完全全新的环境啊

**Comment by rainning123** [comment]
是的 就是点链接（优酷右边的选集）然后就发生这种情况..

**Comment by rainning123** [comment]
通过取消屏蔽底端弹幕 进入的下一集（称之为1） 这一集（1）不会有双弹幕
之后勾选了屏蔽弹幕再进入另一集（2）会有双弹幕
但是在（2）中勾选了屏蔽弹幕回到（1） 1还是正常的没有双弹幕

**Comment by esterTion** [comment]
已更新1.1.11
