### ISSUE TITLE
优酷有几率出现如下错误

### ISSUE THREAD

**Issue by zhanxiage233** [esterTion/Youku-HTML5-Player#30]
测试地址：http://v.youku.com/v_show/id_XMjc4MTkwOTY4NA==.html?spm=a2hww.20023042.m_223473.5~5!2~5~5~A&from=y1.3-idx-beta-1519-23042.223471-223473.2-1
浏览器：360极速8.7 ，chrome58 
都出现了如下错误

![qq 20170524154728](https://cloud.githubusercontent.com/assets/13968052/26392260/8e021818-4098-11e7-8634-75972d7041a4.jpg)

**Comment by zhanxiage233** [comment]
刷新有几率恢复正常播放，再刷新又可能出现同样问题

**Comment by jiangqingg** [comment]
我是大概率出现这个情况，360极速9.0

**Comment by zhanxiage233** [comment]
@jiangqingg 确实是大概率，外链视频也会出现这个问题

**Comment by zhanxiage233** [comment]
像是优酷官方在封杀？firefox上1.1.8也出现同样的问题

**Comment by myfreeer** [comment]
接口坏了

**Comment by OpenWeb321** [comment]
我的就一直这错误，无法播放。。。

**Comment by esterTion** [comment]
大概是开始封了，之后看看

**Comment by Orient-Ea** [comment]
并不是有几率，就是这样了，油猴脚本vipVideos_skipAd也挂了。

**Comment by esterTion** [comment]
神tm多少年没问题的api被我一用给炸了

![](https://camo.githubusercontent.com/12df4364284001fd0cc091309393a6467e77a674/68747470733a2f2f657374657274696f6e2e77696e2f77702d636f6e74656e742f75706c6f6164732f323031372f30352f666136306664373866653464356564383136623962396635353062383739626362353863323136322e6a706567)

已更新1.1.12，同时还添加了视频下载（对就在下载那个按钮里）
换了api后，有的粤剧，比如[吔屎啦，梁非凡！](http://v.youku.com/v_show/id_XMjI2MDUyMDM2.html)的粤语版本就无法播放了，这个是接口数据问题，没办法，只能换flash了
