### ISSUE TITLE
Canvas固定弹幕残留问题

### ISSUE THREAD

**Issue by GoogleGFW** [esterTion/Youku-HTML5-Player#32]
关闭显示弹幕后顶部底部的弹幕会残留在视频上，
CSS绘制弹幕没这个问题，
小问题不影响使用，简单反馈下。
![default](https://cloud.githubusercontent.com/assets/26985927/26437490/18dd48d8-4150-11e7-9798-45336f790960.PNG)

**Comment by esterTion** [comment]
噫，确实
之后改

**Comment by GoogleGFW** [comment]
题外话，应用商店的版本号时空穿越了，1.1.12.3。。。。。。

**Comment by esterTion** [comment]
那个没问题，我昨天上传的时候12.2上传了个光改了版本号，其他js都没动的包，结果占了版本号了

**Comment by esterTion** [comment]
已更新1.2.0
