### ISSUE TITLE
能否像B站那样加入宽屏居中和网页全屏功能？

### ISSUE THREAD

**Issue by nomosaic** [esterTion/Youku-HTML5-Player#33]
RT

**Comment by esterTion** [comment]
并不想加，会很繁琐

**Comment by esterTion** [comment]
说实在，何必把优酷用成b站，本身就不是同类

**Comment by nomosaic** [comment]
@esterTion 我只是希望播放界面大一点 但还不想全屏

**Comment by esterTion** [comment]
网页全屏你自己感受吧
打开console，执行一下document.querySelector('.ABP-Web-FullScreen').click()
爽到飞起

![](https://camo.githubusercontent.com/12df4364284001fd0cc091309393a6467e77a674/68747470733a2f2f657374657274696f6e2e77696e2f77702d636f6e74656e742f75706c6f6164732f323031372f30352f666136306664373866653464356564383136623962396635353062383739626362353863323136322e6a706567)

**Comment by esterTion** [comment]
已更新1.2.3
