### ISSUE TITLE
更新到1.2.1.1失效，1.2.0.1有效

### ISSUE THREAD

**Issue by myskn** [esterTion/Youku-HTML5-Player#35]
已清缓存，试了火狐和chrome的1.2.1.1都失效，火狐是用回flash，chrome是播放器区域白屏
在火狐上退回1.2.0.1，正常使用。

**Comment by esterTion** [comment]
chrome f12 console有没有报错
火狐的话在about:debugging里能看到报错
我用的ff54b11记得测试没问题

**Comment by esterTion** [comment]
找着别人的好像找到问题了
这个扩展和ublock origin有个地方冲突，具体是哪里也不知道，我这边装上ublock也是秒开
你在扩展里禁用一下ublock确认一下能不能打开

**Comment by myskn** [comment]
@esterTion 
可能是ublock的问题吧，我有装，chrome禁用了ublock，刷新一下，正常了，现在开启ublock，也正常。

**Comment by esterTion** [comment]
真的很迷…我拿别人的试也是关一下再开就好了
我自己复制一份也是好的
奇妙
我给readme里加个说明去
