### ISSUE TITLE
无法使用html5

### ISSUE THREAD

**Issue by goohbo** [esterTion/Youku-HTML5-Player#37]
还是flash播放
详情：为啥根本没用？_Firefox_浏览器讨论区 卡饭论坛 - 互助分享 - 大气谦和!
http://bbs.kafan.cn/thread-2091434-1-1.html

控制台报错：
![screenshot00049](https://cloud.githubusercontent.com/assets/12547795/26572015/e6572e48-454a-11e7-987e-bacfcf209afa.png)

**Comment by esterTion** [comment]
浏览器版本
这行报错是配置存储返回了空的，我可能得调一下兼容版本

**Comment by esterTion** [comment]
我看了一下文档，ff52之前好像不支持storage.sync

**Comment by esterTion** [comment]
已更新1.2.1.2，测试仅支持firefox50+

**Comment by goohbo** [comment]
感谢作者，已经正常播放@@@@
