### ISSUE TITLE
uBlock导致youku不能出现播放器的问题

### ISSUE THREAD

**Issue by xinggsf** [esterTion/Youku-HTML5-Player#38]
测试得出：放行tip.soku.com即可，如果还不行，放行g.alicdn.com和log.mmstat.com的东西即可

**Comment by esterTion** [comment]
我试的时候好像是发现cna这个cookie缺失，优酷自己第一次打开也是白屏

**Comment by myfreeer** [comment]
cna可能的来源：`log.mmstat.com/eg.js`

**Comment by esterTion** [comment]
已更新1.2.2
