### ISSUE TITLE
获取视频地址出错

### ISSUE THREAD

**Issue by Jason4774** [esterTion/Youku-HTML5-Player#42]
![20170605_201858](https://cloud.githubusercontent.com/assets/19594338/26783757/7d651698-4a2c-11e7-98d7-6cee77260edb.jpg)
之前还能用，突然就所有优酷视频都不行了

**Comment by julianhu1979** [comment]
我这里也出现了同样的问题。

**Comment by iamggs** [comment]
同样的问题，在`Firefox 53.0.3 (64bit)+xpi 1.2.1.2`和`chrome 58.0.3029.110 (64-bit)+crx 1.2.1.1`下均报这个错。

**Comment by esterTion** [comment]
收到了，一会儿看一下，不保证能解决

**Comment by zhanxiage233** [comment]
+1

**Comment by zhanxiage233** [comment]
@esterTion  我这里自己又恢复正常了

**Comment by iamggs** [comment]
@esterTion 我晕，看完马龙和樊振东的巅峰对决之后发现，又对了。

**Comment by julianhu1979** [comment]
我这里貌似也正常了，好奇怪

**Comment by Jason4774** [comment]
@esterTion 现在正常了。谢谢

**Comment by esterTion** [comment]
懵了，写了一半好了
![](https://camo.githubusercontent.com/12df4364284001fd0cc091309393a6467e77a674/68747470733a2f2f657374657274696f6e2e77696e2f77702d636f6e74656e742f75706c6f6164732f323031372f30352f666136306664373866653464356564383136623962396635353062383739626362353863323136322e6a706567)
之后可能会有个更新
他这次估计是影响到正常用户了，不排除会重来
