### ISSUE TITLE
报错，无法播放~

### ISSUE THREAD

**Issue by Hunlongyu** [esterTion/Youku-HTML5-Player#43]
获取视频地址出错，详细错误：
{"note":"客户端无权播放,201","code":-6004}

我没有用uBlock 插件，但用了类似的 广告过滤插件：净网大师插件版。
但是 即使 关闭了这个插件 也是不行。

**Comment by esterTion** [comment]
首先，无效报错
你浏览器版本和扩展版本都不报

其次，这个问题昨晚已经有更新了
