### ISSUE TITLE
chrome F12 iPhone手机模式报错

### ISSUE THREAD

**Issue by Hunlongyu** [esterTion/Youku-HTML5-Player#44]
Uncaught TypeError: Cannot read property '1' of null
at dom_gen.js:35

因为我也是 前端开发，之前写的代码好好的，今天突然全部报错，吓一跳，但是没有 引用dom_gen.js。
找半天 才发现 是 优酷这个插件 导致的。

虽然我自己的代码没错，但是一直有个红色的报错提示，真真真真 是够了~希望改进~

**Comment by Hunlongyu** [comment]
Youku-HTML5-Player 版本 1.2.2
chrome 版本  58.0.3029.110（正式版本） （64 位）
Windows 10 64位 [版本 10.0.15063]

**Comment by esterTion** [comment]
啊，这行是非chrome就检测firefox版本，没考虑其他情况
之后看一下，这个应该只是每个页面报错一次吧

**Comment by Hunlongyu** [comment]
@esterTion 是的，所有页面 f12 调试都报错。

**Comment by esterTion** [comment]
已更新1.2.2.1
