### ISSUE TITLE
1.2.2出现{"note":"客户端无权播放,201","code":-6004}的错误

### ISSUE THREAD

**Issue by gsy111** [esterTion/Youku-HTML5-Player#48]
获取视频地址出错，详细错误：
{"note":"客户端无权播放,201","code":-6004}

FF 52.02

**Comment by esterTion** [comment]
我这里1.2.2没问题，在浏览器设置里进到`隐私-移除单个cookie`搜索cna，然后删掉youku.com的那个刷新再试试

**Comment by gsy111** [comment]
移除了,还是不行,一样的提示,我的是pcxFirefox 版,和这个有关系吗

**Comment by esterTion** [comment]
有可能……这什么浏览器啊，社区编译版本？
我看一下

**Comment by gsy111** [comment]
https://pcxfirefox.wordpress.com/ 主页

**Comment by julianhu1979** [comment]
今天又出现这个问题了。

**Comment by esterTion** [comment]
不对啊，我下了一个52.0没问题啊，什么情况

**Comment by julianhu1979** [comment]
我是chrome 58有这个问题

**Comment by alextooter** [comment]
firefox53.0.3，Youku-HTML5-Player 1.2.2.1

也是出现这个问题：
ailed fetching video source, error details：
{"note":"客户端无权播放,201","code":-6004}

**Comment by esterTion** [comment]
firefox打开about:debugging，勾选开启调试，点开这个扩展的调试，确定连接后新窗口切到网络，刷新后筛选找到`http://ups.youku.com/ups/get.json`开头的地址，复制一下url贴在这里（右上角有搜索）
chrome直接f12 network找同样的请求贴一下
@gsy111 @julianhu1979 @alextooter

**Comment by esterTion** [comment]
刚才调的时候发现只有空cna的时候才会报无权播放，你们看一下禁用广告屏蔽能不能解决
弹窗逻辑之后可能还需要改动一下
@gsy111 @julianhu1979 @alextooter

**Comment by alextooter** [comment]
我按你说的开了调试，删除ublock，安装abp之后，能看了。 @esterTion 

GET XHR http://ups.youku.com/ups/get.json?ccode=0502&client_ip=127.0.0.1&utid=tp29EZegyUkCAXphpxmgJXcA&client_ts=1496759305462&vid=XMjgwODE2MTg3Ng== [HTTP/1.1 200 OK 149ms]

**Comment by esterTion** [comment]
md，ublock的反跟踪/统计太坑了
现在优酷开始空cna又不能用的样子，之后更新空cna状态直接停止加载了

**Comment by xinggsf** [comment]
@esterTion 跟UBO真没什么关系，我禁用UBO后chrome58还是报无权播放

**Comment by xinggsf** [comment]
提个PR：直接在扩展的内容脚本中XHR下载执行log.mmstat.com/eg.js，取得存入cookie：cna的授权码

**Comment by esterTion** [comment]
@xinggsf 你看看你的是不是无效cna，清cookie看看呢（chrome好像没法单个站点删除）

**Comment by julianhu1979** [comment]
@esterTion 
卸掉ABP之后还是不行，下面是URL

http://ups.youku.com/ups/get.json?ccode=0502&client_ip=127.0.0.1&utid=I95JD3DPrloCAXTACPN%20hlKZ&client_ts=1496793836701&vid=XMjc0NDc5NzAyMA==

**Comment by esterTion** [comment]
…找到问题了
+变成空格了
你试试，%20换%2B就行了…
下次更新修

**Comment by esterTion** [comment]
已更新12.2.2
