### ISSUE TITLE
（性能）（建议）播放器改用clappr？

### ISSUE THREAD

**Issue by alextooter** [esterTion/Youku-HTML5-Player#49]
esterTion，你好，
感谢你写的这个工具，我在使用的时候，发现如果格式是超清的话，鼠标会有点飘，而flash的1080p都不会这样（rmbp15，2013later），怀疑是不是b站的播放器性能问题，我发现一个clappr播放器，感觉性能很强，不知道切换到这个会不会好一点？
该项目地址：https://github.com/clappr/clappr

以上纯属个人感觉，不懂javascript，对性能也不知如何测试。作者大人如果有闲的话研究一下吧，谢谢🙏

**Comment by esterTion** [comment]
解码性能与前段代码关系不大，这个是各个浏览器自己的性能决定的，也不是我所能控制的范围，很抱歉
flash的解码渲染更高效，这个确实不可否认，但chrome致力于“让”flash越来越臃肿缓慢

**Comment by alextooter** [comment]
谢谢。
