### ISSUE TITLE
优酷在使用https的时候 需要点击允许不安全内容，否则会加载失败

### ISSUE THREAD

**Issue by easyinplay** [esterTion/Youku-HTML5-Player#5]
比如：https://v.youku.com/v_show/id_XMjc0NTEyODkyMA==.html?from=y1.3-tv-grid-1007-9910.86827-86824-86821.1-1

报错如下：

播放错误
{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}

能否调整一下，让扩展在https页面下也能正常使用，谢谢

**Comment by easyinplay** [comment]
截图链接： http://i2.muimg.com/1949/f18d830ecf05d196.png

**Comment by esterTion** [comment]
chrome的content script环境会遇到mixed content报错，有一个可以解决的途径但是性能下降很厉害

我晚上加一个判断吧，但还是建议在http下看，因为这种途径会导致播视频极易卡顿

具体细节的话就是通过后台加载，但是从后台到前台的路径在播视频时会特别低效率（解码占cpu最优先），结果就是播放个几秒卡住，卡住的时候后台堆积数据快速输出缓冲几秒然后循环播放卡住的过程

**Comment by easyinplay** [comment]
主要是外链有时候点进来就是Https，如果因为这个牺牲转码性能就得不偿失了，我自己加个重定向吧。

谢谢解答

**Comment by esterTion** [comment]
这个没事，我晚上加个判断chrome+https才起作用的代码，这样其他情况不会有影响
火狐的扩展沙盒并不受mixed content限制

**Comment by esterTion** [comment]
已更新1.0.9
