### ISSUE TITLE
1.2.2.1出现{"note":"客户端无权播放,201","code":-6004}的错误 

### ISSUE THREAD

**Issue by qjzcj2008** [esterTion/Youku-HTML5-Player#50]
扩展程序的版本号1.2.2.1
Chrome版本号58.0.3029.110（正式版本）（64位）
Windows 10 1703 
出现问题的页面：所有
network
![20170606230909](https://user-images.githubusercontent.com/16514953/26836734-384ba79c-4b0e-11e7-90b0-4f26086a57d9.png)
清空cookies，关闭ABP刷新无效，cookies里的cna不为空，但在隐身模式中可以正常运行，清空浏览器缓存、优酷cookies并关闭ABP后在常规模式中重试仍然提示无权播放

**Comment by esterTion** [comment]
get.json的完整地址？

**Comment by esterTion** [comment]
已更新12.2.2，试一下
