### ISSUE TITLE
MediaMSEError，1.2.2.1

### ISSUE THREAD

**Issue by alextooter** [esterTion/Youku-HTML5-Player#51]
今早发现的新问题，有些视频播放不了，弹出错误：
例如：
http://v.youku.com/v_show/id_XNzQ3NDc0NTI4.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0

Playback error
{
  "type": "MediaError",
  "info": "MediaMSEError",
  "detail": {
    "code": 11,
    "msg": "An attempt was made to use an object that is not, or is no longer, usable"
  }
}

macOS 10.12.5,firefox53.0.3,player 1.2.2.1

**Comment by esterTion** [comment]
偶发问题还是每次到某个点都必然触发？
偶发的话可能是网络可能是内存

**Comment by alextooter** [comment]
感觉是老的视频会不行，例如你看2015年上传的视频，十个能遇到一大半不行，
比如这个节目单里面的，随便点几个都会弹出这个错误
http://i.youku.com/i/UMTI5ODg0NTkxMg==?spm=a2h0z.8244218.2371631.d6373

**Comment by esterTion** [comment]
问了下flvjs作者说你这个是解码错误……
这个确实无能为力，不好意思
我这边测试几个都能播放

**Comment by alextooter** [comment]
新的视频播放还行，优酷和土豆都搬到阿里云上了，各种改接口。
