### ISSUE TITLE
v-wb.youku.com还是flash

### ISSUE THREAD

**Issue by w153140** [esterTion/Youku-HTML5-Player#54]
这个网址还是flash播放http://v-wb.youku.com/v_show/id_XMjgyMTEwODA0OA==.html?x&sharefrom=android

**Comment by esterTion** [comment]
这个地址从哪跳的，从来没见过这域名

**Comment by gsy111** [comment]
微博跳转,我今天也遇到了

**Comment by w153140** [comment]
@esterTion 微博分享的

**Comment by esterTion** [comment]
已更新1.2.3.2
