### ISSUE TITLE
覆盖官方HTML5播放器

### ISSUE THREAD

**Issue by gaoyifan** [esterTion/Youku-HTML5-Player#55]
由于官方HTML5播放器远没有Youku-HTML5-Player好用。另，在连续播放剧集时，每次切换到下一个视频都需要手动点击“切回旧版播放器”，比较繁琐。
希望能增加一个选项，允许默认替换掉官方的HTML5播放器。

**Comment by esterTion** [comment]
啊，你是mac吗
更新的时候忘了mac的默认

**Comment by gaoyifan** [comment]
是的。
macOS Sierra 10.12.5 (16F73)
Chrome 59.0.3071.86

**Comment by esterTion** [comment]
ok，晚上我看下把mac的ua替换一下装作win，这样就可以开关控制了
顺便把另一个到时候更上去

**Comment by gaoyifan** [comment]
非常感谢！

**Comment by gaoyifan** [comment]
顺便一提 macOS+Chrome的UA是：
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
```

**Comment by esterTion** [comment]
已更新1.2.3.2
