### ISSUE TITLE
默认是优酷的HTML5播放器

### ISSUE THREAD

**Issue by zhaowweny** [esterTion/Youku-HTML5-Player#57]
不知道什么时候开始，播放器默认变成优酷的HTML播放器了，然后播放窗口左上角有一个返回旧版播放器，点击才可以使用B站的播放器了。

**Comment by esterTion** [comment]
更新扩展

**Comment by zhaowweny** [comment]
我的已经是最新版了，重新安装也不行。我的是Mac，chrome版本是58.0.3029.110，谢谢！

**Comment by esterTion** [comment]
mac我测试过是可以替换的
正常启用扩展的情况下，页面里控制台输入`navigator.userAgent`里面mac有没有被替换掉

**Comment by zhaowweny** [comment]
我试了下，不管是官方的播放器还是手动切换成B站的播放器，那个参数都是："Mozilla/5.0 (intosh; Intel  OS X
10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104
Safari/537.36"。

**Comment by esterTion** [comment]
实测10.12.5+59.0.3071.104正常工作，确认一下你没有用其他的强制开启官方播放器的脚本

**Comment by zhaowweny** [comment]
我把油猴的脚本都关了，还是不行，今天点击那个切回旧版播放器都不行了，还是官方的播放器。

**Comment by zhaowweny** [comment]
我找到原因了，是广告终结者这个扩展导致的，不知道有没有什么比较两全其美的解决办法。
