### ISSUE TITLE
请问报错Access-Control-Allow-Origin怎么做？

### ISSUE THREAD

**Issue by goldmonkey163com** [esterTion/Youku-HTML5-Player#61]
不好意思，只找到您这儿有相关的问题分析，所以想问下您。
关于您说的：“部分视频cdn跨域配置不正确会导致无法播放，遇到console报错Access-Control-Allow-Origin相关请联系优酷，并带上cdn ip地址报错”
想问下一个是怎么样知道cdn的ip地址。。。我本来还以为把自己的dns改了就行。。。
第二个有没有优酷的有效联系方式，仅仅通过http://csc.youku.com/feedback-web/web 不知道够不够。。。

**Comment by esterTion** [comment]
![](https://user-images.githubusercontent.com/7265411/27430412-0d680524-577b-11e7-8676-959a8cb516b8.png)
