### ISSUE TITLE
不更了？

### ISSUE THREAD

**Issue by xinggsf** [esterTion/Youku-HTML5-Player#62]
@esterTion
提个问：我用你的这个扩展框架写CCTV的，但运行时提示abpinst未定义（非ABPInst）搜索你的扩展全部文件也未找到，还望不吝赐教

**Comment by esterTion** [comment]
[youku_html5.js:664](https://github.com/esterTion/Youku-HTML5-Player/blob/master/youku_html5.js#L664)

**Comment by xinggsf** [comment]
全局变量？和ABPInst有什么区别？

**Comment by esterTion** [comment]
ABPInst是创建时的内部变量，在最后被输出，然后外部命名abpinst

**Comment by xinggsf** [comment]
找到问题所在了：我把弹幕库CommentCoreLibrary省略了
现在还未能呈现播放器，弹出提示不能在null对象设置className

**Comment by xinggsf** [comment]
感觉ABPlayer播放器封装得不够

**Comment by esterTion** [comment]
我早期改的一些是瞎改的，所以外部用其他名字的时候估计各种问题…

**Comment by xinggsf** [comment]
@esterTion 
弹出错误提示：MediaDataSource must has type field to indicate video file type!
创建flvplayer实例失败，然后控制台一直输出：flvplayer is not defined
你有遇到这样的问题吗？

**Comment by esterTion** [comment]
[flv.js/api.md](https://github.com/esterTion/flv.js/blob/master/docs/api.md)

**Comment by xinggsf** [comment]
你的代码：`self.flvplayer = flvjs.createPlayer(e.detail.src, e.detail.option);`
MediaDataSource类型定义？`{type: mp4;duration:6e5}` 这样可以吗？

**Comment by esterTion** [comment]
type mp4还要啥flvjs
搞分段的话就type flv就行了，格式处理会自动识别，segment里给好长度

**Comment by xinggsf** [comment]
是分段MP4啊！

**Comment by esterTion** [comment]
是，外部配置里我加了个segment-mp4，但实际上因为这个type传不到解封装那里，所以没区别
我自己用的就直接type flv，表示使用mse而不是浏览器native mp4

**Comment by xinggsf** [comment]
弹出：播放错误
```javascript
{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}```

**Comment by xinggsf** [comment]
控制台：
Fetch API cannot load http://vod.cntv.lxdns.com/flash/mp4video25/TMS/2012/12/13/fc9bd251c764479ba5ddcdca80be57bd_h264818000nero_aac32-1.mp4. Redirect from 'http://vod.cntv.lxdns.com/flash/mp4video25/TMS/2012/12/13/fc9bd251c764479ba5ddcdca80be57bd_h264818000nero_aac32-1.mp4' to 'http://182.108.171.171/vod.cntv.lxdns.com/flash/mp4video25/TMS/2012/12/13/f…_aac32-1.mp4?wshc_tag=0&wsts_tag=595b5135&wsid_tag=73961bb1&wsiphost=ipdbm' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tv.cntv.cn' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

不是扩展有特权的吗

**Comment by esterTion** [comment]
[manifest.json:77](https://github.com/esterTion/Youku-HTML5-Player/blob/master/manifest.json#L77)

**Comment by xinggsf** [comment]
@esterTion 重定向后特权就没了，有什么办法将flvjs中fetch的mode设置为no-cors

**Comment by xinggsf** [comment]
帮忙看看这句哪有错误：
```javascript
chrome.webRequest.onHeadersReceived.addListener(e => {
    return {responseHeaders : [
        {name:'Access-Control-Allow-Origin',value: '*'},
        {name:'Access-Control-Allow-Headers',value: 'Range'}
    ]}},
    {urls: [{pathPrefix: '/vod.cntv.lxdns.com/flash/'} ], types: ['xmlhttprequest']},
    ["responseHeaders","blocking"]
);
```

**Comment by esterTion** [comment]
怎么会重定向就没了…优酷全是302的，应该说基本没哪家是直链的
你是怎么实现的，flvjs放扩展外边script了？扩展里的时候视频fetch根本就不是跨域请求

**Comment by esterTion** [comment]
![qq 20170704222736](https://user-images.githubusercontent.com/7265411/27834089-1a10fb64-6108-11e7-99aa-6f8488de3c6a.png)
![qq 20170704222746](https://user-images.githubusercontent.com/7265411/27834093-1d6394f2-6108-11e7-80ac-c24afaa2a0d4.png)
![qq 20170704222756](https://user-images.githubusercontent.com/7265411/27834096-1fdc4fc6-6108-11e7-99ce-04d12eeef1c9.png)
你看看，从开始到200，没有一个有origin，access-control，扩展内部发出的fetch全部视作同域请求

**Comment by esterTion** [comment]
[Host Permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions): `XMLHttpRequest and fetch access to those origins without cross-origin restrictions (even for requests made from content scripts)`

**Comment by xinggsf** [comment]
用了多线程就没特权了！！

**Comment by xinggsf** [comment]
@esterTion flvjs又出问题了，错误提示：
flv.min.js:6 [IOController] > Loader error, code = undefined, msg = Invalid array length

先谢谢你的热心回复

**Comment by xinggsf** [comment]
看来只能试试hls了
