### ISSUE TITLE
"NetworkError, Failed to fecth" caused by Adblock plus

### ISSUE THREAD

**Issue by ZhuXiaomin** [esterTion/Youku-HTML5-Player#64]
### Play youku video failed

播放错误
{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}

### Reason:
Get url below failed: `ERR_BLOCKED_BY_CLIENT`
http://58.216.103.47/youku/6975CB805D039830BA79AD537F/0300010100595E3EC4A7C107A39AA6A16FF91D-B00A-6B08-B959-FC722D046CA5.flv?sid=049943329068212a8e51b&ctype=12&ccode=0502&duration=180&expire=18000&psid=3fd58cafdb1138e54a36d07f21b40ead&ups_client_netip=183.156.115.158&ups_ts=1499433290&ups_userid=47955180&utid=1fdzEVMV0BcCAX14VCxCGzHt&vkey=Ab4d04ca61b1b9acdf6f44901a5f378e6&vid=XMjg3MzI4MjMyOA%3D%3D

### Solution:
Add  filtering rule in Adblock plus: 
```
@@||58.216.103.47/youku/*
```

**Comment by esterTion** [comment]
匹配了什么奇葩规则…哪个智障屏蔽广告把所有视频源都干了吗

**Comment by ZhuXiaomin** [comment]
Update:
`@@||*/*/*.flv?*`

看了一下，视频源基本是这样的url，目前只有手动加上例外的规则了。

**Comment by esterTion** [comment]
匹配了这个
`/\:\/\/([0-9]{1,3}\.){3}[0-9]{1,3}/$third-party,xmlhttprequest`
emmm，这有病的规则谁提交的，就该打死

**Comment by xinggsf** [comment]
> emmm
竟然有如此奇葩的规则

**Comment by esterTion** [comment]
问题已解决，请更新adblock规则
[EasyList Topic](https://forums.lanik.us/viewtopic.php?f=64&t=37420)
[Wrong commit](https://github.com/easylist/easylist/commit/ae085656c9ce1c3b68bea4519dd0585bac15f0dc)
[Fix commit](https://github.com/easylist/easylist/commit/95229bebe6e20b39ce179ea4941ffbdde144325a)
