### ISSUE TITLE
{"note":"客户端无权播放,201","code":-6004} 

### ISSUE THREAD

**Issue by billzt** [esterTion/Youku-HTML5-Player#68]
页面：任何页面，例如 http://v.youku.com/v_show/id_XMjg4MTAyMjUxMg==.html?spm=a2hww.20023042.ykRecommend.5~5~5!2~5~A

使用的浏览器、版本以及扩展的版本：Firefox 54.0.1，扩展1.2.5.5，

**Comment by esterTion** [comment]
优酷日常策略抽风，看起来已经恢复

**Comment by billzt** [comment]
刚才试了一下 没有恢复

**Comment by heheql** [comment]
十分钟前还正常，刚刚又出问题了
{"note":"客户端无权播放,201","code":-6004}

**Comment by msghost** [comment]
同样的问题，禁用ublock似乎无效，而且我是在视频播放中出的问题。

**Comment by heheql** [comment]
我怀疑是不是 因为 开了原画， 然后这应该是优酷会员看的，我们没有这个权限看，接着默认的就是原画

**Comment by esterTion** [comment]
@heheql
跟这个没关系
接口整个全部过来，跟默认没关系

**Comment by esterTion** [comment]
已更新1.2.6.1

**Comment by heheql** [comment]
辛苦了！
