### ISSUE TITLE
客户端无权播放，201， code -6004

### ISSUE THREAD

**Issue by XingwenZhang** [esterTion/Youku-HTML5-Player#69]
firefox 版本， 54.0.1（32-bit），其他插件：NetVideoHunter，关闭此插件，优酷依然无法播放视频。求解决啊^_^

**Comment by esterTion** [comment]
其他扩展不归我管，我也管不到

**Comment by esterTion** [comment]
如果你是指官方放不了，找客服

**Comment by XingwenZhang** [comment]
额，你理解错了。。。。我意思是除了youku html5 player这个插件，我关闭其他插件，还是不能播放，（排除其他插件的影响）。如果不使用你的插件的话，视频是可以播放的。

**Comment by esterTion** [comment]
哦哦这个意思
扩展版本多少

**Comment by XingwenZhang** [comment]
1.2.5.5

**Comment by esterTion** [comment]
更新一下版本，现在是1.2.6.1

**Comment by XingwenZhang** [comment]
OK, solved
