### ISSUE TITLE
要是有弹幕就更好了

### ISSUE THREAD

**Issue by gsy111** [esterTion/Youku-HTML5-Player#7]
要是有弹幕就更好了

**Comment by esterTion** [comment]
怎么说呢……我花了半个小时把弹幕模块从播放器代码里删掉了……懒癌发作严重不想再加了
如果有兴趣贡献的话可以从[live_html5_lib](https://github.com/esterTion/live_html5_lib)里面看，那个我把所有js都pack到一起了，CommentCoreLibrary以及屏蔽模块shield
主要是各种删功能再加回去很麻烦

**Comment by gsy111** [comment]
OMG!

**Comment by esterTion** [comment]
懒癌还是比较重，或许我周末会看看重新加上
其实更简单的方法是再把我之前的未删改代码直接复制一份再把改动加上
总之这个暂时先放着，包括另一个片头片尾的中午也是懒得整，计划是准备加上播放的

**Comment by esterTion** [comment]
想了想又发觉要写弹幕的话还得整上发送，复杂度瞬间上升
![](https://estertion.win/wp-content/uploads/2017/05/87a37574a16637823a3cb54a352c8a0a1c19816c.jpg)
果然还是算了

**Comment by gsy111** [comment]
能看弹幕就行,我只看弹幕
<img src='http://i1.piimg.com/1949/7927367a80be0be8.jpg'>

**Comment by esterTion** [comment]
已更新1.1.0
