### ISSUE TITLE
咨询一下FF市场上面的更新一般晚于github多少时间

### ISSUE THREAD

**Issue by msghost** [esterTion/Youku-HTML5-Player#70]
最近才发现这个插件，感谢作者的贡献，看优酷终于不卡了。。还没有广告，美滋滋。。
想咨询一下，github更新后，一般FF市场多久会跟进版本呢，因为觉得FF市场上安装的插件可以直接多设备同步，不用重复安装比较方便。
谢谢，祝好！

**Comment by esterTion** [comment]
ff市场审核时间很不确定的，一般来讲的话会在3-7天,有时候还会退回来让我提供源码(在我已经注明github仓库的情况下)
市场的话底下有一个开发通道,每次提交的时候我会同时提交一个pre版本号的版本,内容是一样的,那个通道不用审核,而且应该也能同步

**Comment by msghost** [comment]
根据你的提示，已经找到这个开发通道并安装。非常感谢你的杰出工作，谢谢！

**Comment by ivysrono** [comment]
@esterTion 由于审核原因，上架版无法继续更新
这是什么意思？是过审版永远不更新了，还是要等审核比较慢？

**Comment by esterTion** [comment]
@ivysrono
永远不更新了
1.2.6为了确保获取地址时有优酷页面的来源，换成了script+jsonp获取，然后审核被拒绝，因为引入第三方脚本按照审核规范是不安全行为（无法审核第三方脚本内容）
我之前几天曾经试过换成自己添加跨域头，提交审核后还是拒绝，因为跨域头不允许修改
所以以后火狐只有`上架版开发通道`和`自分发`

**Comment by ivysrono** [comment]
@esterTion 今天看到审核版又更新了，情况发生变化了？

**Comment by esterTion** [comment]
改了地址获取方式，现在不冲突了

其实这次审核卡了我好久，结果今天开始突然变成机器自动审核了，大概以后和chrome一个情况了

**Comment by ivysrono** [comment]
@esterTion 连icon都改了……
喜忧参半啊~

**Comment by esterTion** [comment]
？？？
icon早改了啊，amo是我账号的所以改的很早了，chrome是最近转移的我才改

**Comment by msghost** [comment]
我觉得有开发版通道就OK了，正式版无所谓的，反正都能够正常更新就完了。

**Comment by ivysrono** [comment]
不是指扩展，我是说amo的icon改得好奇怪

**Comment by esterTion** [comment]
哦，amo图标啊
mozilla这阵要闹死，到处都在改ui，从ff到mdn到amo
混乱之后chrome或成最大赢家
