### ISSUE TITLE
放着放着弹框提示HttpStatusCodeInvalid

### ISSUE THREAD

**Issue by qw4096** [esterTion/Youku-HTML5-Player#73]
弹框内容：
播放错误
{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 502,
    "msg": "Bad Gateway"
  }
}
播放器变灰，提示加载视频失败，无法播放该视频
关闭弹框，播放器上的提示仍然没有消失，视频也无法播放，只能刷新

**Comment by qw4096** [comment]
刚注意到说明，是ublock的问题

**Comment by esterTion** [comment]
这个应该不是ublock，是优酷服务器问题
遇到确实只能刷新，也没有别的办法

**Comment by qw4096** [comment]
好吧，只能先这样了。最近才出这事，原生HTML5播放器经常放着放着就卡着不动了，不知道搞什么鬼，想用flash现在又被检测到广告拦截，等待45s

**Comment by qw4096** [comment]
刚刚又多了这么一种情况
{
  "type": "NetworkError",
  "info": "UnrecoverableEarlyEof",
  "detail": {
    "code": 403,
    "msg": "Forbidden"
  }
}
另外补充说明一下，这两种情况都是播放器变灰（其实应该是亮度变低），提示加载视频失败，无法播放该视频，但实际上播放并不受影响，就是亮度变低没法看了

**Comment by esterTion** [comment]
类似就自己刷新吧，也有播放位置记录

（是不是我当时写成出啥错强制停止播放你们就不来报问题而是直接刷新了

**Comment by LakeishaKowalczyk** [comment]
@esterTion 出现过于频繁，应该是有什么问题，基本每集都会出现一两次．
先是「高清加载失败，转到标清画质」，然后就是「加载视频失败，无法播放该视频」
https://v.youku.com/v_show/id_XNTIzNDQ0NjA0.html

每一集都要重新刷新，这不能不当作一个问题吧
