### ISSUE TITLE
[Feature Request] 是否可以上 Opera 的扩展商城？

### ISSUE THREAD

**Issue by passerbyxp** [esterTion/Youku-HTML5-Player#74]
目前我是下载下来之后直接拖放到 Opera 里使用的，实测无问题，应该对 Opera 版的 Blink 是兼容的，就希望可以上 Opera 官方的扩展商城，这样就可以自动更新了

**Comment by esterTion** [comment]
行，我之后看一下有什么条件

**Comment by esterTion** [comment]
看了下发布规范，基本上确定会被驳回
因为能稳定获取视频地址的方式会违反安全规定（引入外部代码执行）
他们不管你要干什么，来源可不可信，第三方就不行

**Comment by passerbyxp** [comment]
好的，那我继续用目前的方法吧。谢谢！

**Comment by esterTion** [comment]
事实上，我刚刚测试了一下，直接点`crx分流`可以安装，并且会自动通过chrome商店更新
不知道你是不是需要一个免墙的自动更新服务，是的话我可以独立出来一个nex+更新xml
（现在的opera简直是chrome的皮肤包）

**Comment by passerbyxp** [comment]
我没试过直接点，明天试试。
梯子我常备，暂时不需要啦。我也知道 Opera 现在只是一个 Chrome 皮肤，所以才会直接拖放 crx 安装 :)
