### ISSUE TITLE
观看一段时间后，缓冲速度无速度

### ISSUE THREAD

**Issue by lurora** [esterTion/Youku-HTML5-Player#76]
开始时缓冲速度2m/s，缓冲至180s后停止缓冲，播放到30s后再次缓冲到180s，之后缓冲速度一直为零，180s播完了也没反应。刷新网页后重复以上过程，原画和高清都这样，发生概率100%，没有其他扩展在干扰。

**Comment by esterTion** [comment]
正常工作
浏览器允许的缓冲有限，只能这样按需缓冲

**Comment by lurora** [comment]
那一段时间后缓冲无速度怎么办呢？好像不能自动清理缓冲啊，需要手动刷新

**Comment by esterTion** [comment]
就是6分钟就不放了？
f12 console有什么报错截个图

**Comment by lurora** [comment]
![20170813171930](https://user-images.githubusercontent.com/30972308/29248467-9f8b4d82-804b-11e7-83a7-401679aba66a.png)
是这个吗？

之前问没把问题表述清楚，我遇到的问题是6分钟后无法继续缓冲

**Comment by lurora** [comment]
我再测试测试，好像跟广告插件有点关系

**Comment by esterTion** [comment]
……妈的，前阵abp的智障规则是不是又更新上去了
你把abp关了看看

**Comment by esterTion** [comment]
手机还没法编辑…打错了，adblock

**Comment by lurora** [comment]
我多试试。。。。等会儿。。。

**Comment by esterTion** [comment]
而且用的https？http有没有问题

**Comment by lurora** [comment]
![20170813174446](https://user-images.githubusercontent.com/30972308/29248612-22c7443c-804f-11e7-8ff6-b61d7228a25e.png)
![20170813174944](https://user-images.githubusercontent.com/30972308/29248648-d0dbec6c-804f-11e7-8bee-45c5f04d7063.png)
我打开的好像是https网站？不是很清楚
这是开了广告屏蔽插件（我同时开启了ADB和广告终结者），6分钟之后的截图，我看到缓存还剩30S的时候console这个里面多了几项，你看看
我再去关掉广告插件试试

**Comment by esterTion** [comment]
我之后研究下，有点奇怪，应该啥变了

**Comment by lurora** [comment]
![da](https://user-images.githubusercontent.com/30972308/29248856-0dbf939a-8055-11e7-80c3-04fdc5bec47f.png)
我关掉了其它所有插件
好像跟广告插件没关系，是http和https的问题
上图左边是http，我播了一会，一直是正常的
上图右边是https，6分钟后就不能继续缓存了


我再观察了下，发现到6分钟的时候http和https的console都出现了`http cdn地址无效，尝试m3u8`
http之后`load backup url for segment 7`
然后出现Loader error，再load backup url for segment 8，这好像是一直在用backup url？

而https出现`http cdn地址无效，尝试m3u8`后，没有load backup url
而是出现了
```
Uncaught (in promise) TypeError: r.text is not a function
    at youku_html5.js:582
    at <anonymous>
```
PS:https在我测试的时候还让我加载了个不安全的脚本，我加载了，没用

**Comment by lurora** [comment]
用http就能正常播放了

**Comment by esterTion** [comment]
已更新1.2.7

**Comment by Goshin** [comment]
@esterTion 

1.2.8.4 似乎又有这个问题。

在 http 下，播放到 20 分钟左右，每隔几分钟，缓冲速度降为 0，刷新后能继续播放。有时会提示 failed to fetch，https 下未测试。

![image](https://user-images.githubusercontent.com/10056397/29832802-f2f6a0b6-8d1b-11e7-8d9f-3c3f8f5eb7d3.png)

```javascript
{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}
```


![image](https://user-images.githubusercontent.com/10056397/29832948-6c42f776-8d1c-11e7-9ecc-93fc05e2732d.png)

需要的话可以再附上视频链接和详细的日志。

**Comment by esterTion** [comment]
@Goshin
网络问题，无法连到这个分段所在服务器，无解
切换清晰度可以缓解

**Comment by Goshin** [comment]
好的，我在确认一下。
