### ISSUE TITLE
firefox 57 nightly 不加载视频

### ISSUE THREAD

**Issue by GithubUsername3** [esterTion/Youku-HTML5-Player#77]
firefox55正式版正常，57nightly一直停在"正在加载视频信息"
不知道是fx测试版暂时的待修复的bug，还是长久性bug需要本扩展适应的

**Comment by esterTion** [comment]
确认有这个问题，具体原因是`HTMLElement.prototype.tooltip`函数设置后不知道在哪里丢失了
我调试的感觉是优酷哪个js影响，但是按理外部js不应该影响扩展内的变量

**Comment by esterTion** [comment]
已更新1.2.8
