### ISSUE TITLE
chrome49使用最新的1.2.8.1版本无效

### ISSUE THREAD

**Issue by fjyts77** [esterTion/Youku-HTML5-Player#78]
WIN10 64位系统，32位chrome49使用最新的1.2.8.1版本无效，仍然是FLash播放，以前使用旧版本（1.2.6）正常
http://r1.ykimg.com/material/0A05/ad/619ff20c53e10f0c22c7edb3b13c56d2/p.main.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html:272 Uncaught ReferenceError: YK_CPA is not defined
https://g.alicdn.com/alilog/aplus_cplugin/0.1.2/ls.html?_a_ig_p_url=http%3A…d_XMjk5MDU0NDczNg%3D%3D.html%3Fspm%3Da2hww.20023042.m_223473.5~5!2~5!2~5~A Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
comment_load_18.js:5 现在是：V3 全量
(program):160 undefined
http://static.youku.com/index/js/ikuAdapterNew.js?_=1503708742981 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…&ref=http%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=320&_=1503708742983 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…&ref=http%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=321&_=1503708742984 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…&ref=http%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=322&_=1503708742985 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…&ref=http%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=323&_=1503708742986 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=324&vl=2976.80&_=1503708742987 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…&ref=http%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=327&_=1503708742988 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://b.scorecardresearch.com/b?c1=2&c2=6035715&rn=0.02689257968601022&c7=…5%9C%A8%E7%BA%BF%E8%A7%82%E7%9C%8B&c9=http%3A%2F%2Fwww.youku.com%2F&cv=1.7 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://irs01.net/MTFlashStore.swf# Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://tip.soku.com/searches/soku/kubox/v4/sideads.json?jsoncallback=XBox.gUpdate&site=14&t=1503708747921 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
countweb?uid=1152329208&callback=tuijsonp9:1 Uncaught SyntaxError: Unexpected token :
lib_13.js:7 GET http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…tp%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=1430192600&_=1503708742999 net::ERR_BLOCKED_BY_CLIENTsend @ lib_13.js:7p.extend.ajax @ lib_13.js:7p.(anonymous function) @ lib_13.js:7p.extend.getScript @ lib_13.js:7e.extend.addAD @ index_153.js:9e.extend.addrelationListAd @ index_153.js:9(anonymous function) @ index_153.js:12a @ g_69.js:5p.event.dispatch @ lib_13.js:6g.handle @ lib_13.js:6p.event.trigger @ lib_13.js:6(anonymous function) @ lib_13.js:6p.extend.each @ lib_13.js:5p.fn.p.each @ lib_13.js:5p.fn.extend.trigger @ lib_13.js:6n.(anonymous function) @ g_69.js:5e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
lib_13.js:7 GET http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…tp%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=1430192617&_=1503708743000 net::ERR_BLOCKED_BY_CLIENTsend @ lib_13.js:7p.extend.ajax @ lib_13.js:7p.(anonymous function) @ lib_13.js:7p.extend.getScript @ lib_13.js:7e.extend.addAD @ index_153.js:9e.extend.addrelationListAd @ index_153.js:9(anonymous function) @ index_153.js:12a @ g_69.js:5p.event.dispatch @ lib_13.js:6g.handle @ lib_13.js:6p.event.trigger @ lib_13.js:6(anonymous function) @ lib_13.js:6p.extend.each @ lib_13.js:5p.fn.p.each @ lib_13.js:5p.fn.extend.trigger @ lib_13.js:6n.(anonymous function) @ g_69.js:5e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
lib_13.js:7 GET http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…tp%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=1464781393&_=1503708743001 net::ERR_BLOCKED_BY_CLIENTsend @ lib_13.js:7p.extend.ajax @ lib_13.js:7p.(anonymous function) @ lib_13.js:7p.extend.getScript @ lib_13.js:7e.extend.addAD @ index_153.js:9e.extend.addrelationListAd @ index_153.js:9(anonymous function) @ index_153.js:12a @ g_69.js:5p.event.dispatch @ lib_13.js:6g.handle @ lib_13.js:6p.event.trigger @ lib_13.js:6(anonymous function) @ lib_13.js:6p.extend.each @ lib_13.js:5p.fn.p.each @ lib_13.js:5p.fn.extend.trigger @ lib_13.js:6n.(anonymous function) @ g_69.js:5e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
lib_13.js:7 GET http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…tp%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=1464781428&_=1503708743002 net::ERR_BLOCKED_BY_CLIENTsend @ lib_13.js:7p.extend.ajax @ lib_13.js:7p.(anonymous function) @ lib_13.js:7p.extend.getScript @ lib_13.js:7e.extend.addAD @ index_153.js:9e.extend.addrelationListAd @ index_153.js:9(anonymous function) @ index_153.js:12a @ g_69.js:5p.event.dispatch @ lib_13.js:6g.handle @ lib_13.js:6p.event.trigger @ lib_13.js:6(anonymous function) @ lib_13.js:6p.extend.each @ lib_13.js:5p.fn.p.each @ lib_13.js:5p.fn.extend.trigger @ lib_13.js:6n.(anonymous function) @ g_69.js:5e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
lib_13.js:7 GET http://v2html.atm.youku.com/vhtml?t=1503708744088&rst=swf,img&ct=d&cs=2038|…tp%3A%2F%2Fwww.youku.com%2F&sid=1boe0d2cq1nie&p=1464781466&_=1503708743003 net::ERR_BLOCKED_BY_CLIENTsend @ lib_13.js:7p.extend.ajax @ lib_13.js:7p.(anonymous function) @ lib_13.js:7p.extend.getScript @ lib_13.js:7e.extend.addAD @ index_153.js:9e.extend.addrelationListAd @ index_153.js:9(anonymous function) @ index_153.js:12a @ g_69.js:5p.event.dispatch @ lib_13.js:6g.handle @ lib_13.js:6p.event.trigger @ lib_13.js:6(anonymous function) @ lib_13.js:6p.extend.each @ lib_13.js:5p.fn.p.each @ lib_13.js:5p.fn.extend.trigger @ lib_13.js:6n.(anonymous function) @ g_69.js:5e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
g_69.js:7 GET http://irs01.com/irt?_iwt_id=&_iwt_UA=UA-youku-000001&jsonp=MTJ6SLD6RD124LSZ&_iwt_p1=&_iwt_p2=&_iwt_p3=& net::ERR_BLOCKED_BY_CLIENTM @ g_69.js:7_.track @ g_69.js:6(anonymous function) @ g_69.js:6
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 GET http://valf.atm.youku.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 GET http://ali.irs01.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
index_153.js:8 GET http://r.l.youku.com/rec_ad_show?logVersion=1&visitTime=1503708761588&ip=0&…eq_id=NQAXJ599I_Mnux&vid=undefined&apt=1&pg=3&md=1&adnum=0&advid1=&advid2= net::ERR_BLOCKED_BY_CLIENTsetTimeout (async)e.extend.showCallback @ index_153.js:8(anonymous function) @ index_153.js:8d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
index_153.js:9 GET http://r.l.youku.com/rec_ad_show?logVersion=1&visitTime=1503708762465&ip=0&…eq_id=NGl3sMxB6_BGZD&vid=undefined&apt=1&pg=3&md=1&adnum=0&advid1=&advid2= net::ERR_BLOCKED_BY_CLIENTsetTimeout (async)e.extend.likeShowCallback @ index_153.js:9(anonymous function) @ index_153.js:9d @ lib_13.js:5u.fireWith @ lib_13.js:5C @ lib_13.js:7t.onload.t.onreadystatechange @ lib_13.js:7
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 GET http://ali.irs01.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 GET http://ali.irs01.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 POST http://pss.alicdn.com/iku/log/acc net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 POST http://pss.alicdn.com/iku/log/acc net::ERR_BLOCKED_BY_CLIENT
id_XMjk5MDU0NDczNg==.html?spm=a2hww.20023042.m_223473.5~5!2~5!2~5~A:1 GET http://valc.atm.youku.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
http://ykatr.youku.com/atr/related/packed_list.json?site=1&guid=14943363433…97&pg=1&callback=jQuery111208420861774892707_1503708742996&_=1503708742997 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
index.js:1 'Document.defaultCharset' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6217124578066432 for more details.
219.145.210.167:4466/crossdomain.xml:1 GET http://219.145.210.167:4466/crossdomain.xml net::ERR_CONNECTION_TIMED_OUT
98.js:10 GET http://valp.atm.youku.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ 98.js:10(anonymous function) @ 98.js:10r @ 98.js:10
pss.alicdn.com/iku/log/acc:1 POST http://pss.alicdn.com/iku/log/acc net::ERR_BLOCKED_BY_CLIENT
pss.alicdn.com/iku/log/acc:1 POST http://pss.alicdn.com/iku/log/acc net::ERR_BLOCKED_BY_CLIENT

**Comment by esterTion** [comment]
能截图吗…排版全乱了，而且好像没看到有扩展报错

**Comment by fjyts77** [comment]
这是使用1.2.8.2版本的图，仍然没启用成功

**Comment by fjyts77** [comment]
![qq 20170826195718](https://user-images.githubusercontent.com/3735840/29741119-060dbcbe-8a99-11e7-940c-5c502acc09af.png)

**Comment by esterTion** [comment]
![qq 20170826202050](https://user-images.githubusercontent.com/7265411/29741298-562f1e74-8a9c-11e7-9385-7a1013279c5b.png)

> Seems this is a bug and is supposed to be fixed in Chrome 50, according to the bug report: <https://bugs.chromium.org/p/chromium/issues/detail?id=63979>

emmm，更新一下吧

**Comment by esterTion** [comment]
目前的话两种解决
升级chrome
或者扩展降级[1.2.7](https://github.com/esterTion/Youku-HTML5-Player/blob/952dc1b93ddc66e2f70085770fd3add944d0a082/signed.crx?raw=true)
降级后，把`%appdata%\..\Local\Google\Chrome\User Data\Default\Extensions\fpnknfakcmgkbhccgpgnbaddggjligol`目录的写入权限整体去掉可以避免更新，步骤可搜索

**Comment by fjyts77** [comment]
好的，十分感谢

**Comment by esterTion** [comment]
刚才已经更新了1.2.8.3，把版本提高到50.0了，要使用旧版本的话应该不需要再操作文件夹权限了
