### ISSUE TITLE
获取视频地址出错

### ISSUE THREAD

**Issue by NoWhereMee** [esterTion/Youku-HTML5-Player#79]
获取视频地址出错，详细错误：
{"note":"客户端无权播放,201","code":-6004}
![image](https://user-images.githubusercontent.com/25219963/29910982-bd4d79e6-8e5e-11e7-9332-da75d8d8ed06.png)

**Comment by esterTion** [comment]
[测试](http://v.youku.com/v_show/id_XMTU1MDcxNDIyOA==.html?debug=flv)没问题
![qq 20170901142103](https://user-images.githubusercontent.com/7265411/29957572-ceb344dc-8f20-11e7-9bc9-46b0d9cbc66d.jpg)

**Comment by NoWhereMee** [comment]
找到可行的方案了 需要清除cookie 目前已经恢复 谢谢
