### ISSUE TITLE
YouTube主题和YouTube的差别好大啊🤣

### ISSUE THREAD

**Issue by zhaowweny** [esterTion/Youku-HTML5-Player#83]
<img width="850" alt="youtube" src="https://user-images.githubusercontent.com/4287088/30141813-3db10ff2-93b0-11e7-8089-a1092a5389b8.png">
<img width="955" alt="youtube" src="https://user-images.githubusercontent.com/4287088/30141814-3e22fd92-93b0-11e7-8a2e-345a780bd720.png">

原谅我看不出来是YouTube主题😊尤其是按钮图标好大啊

**Comment by esterTion** [comment]
差距还是有的，主题主要意思就是半透明控制栏背景+按钮位置布局
图标大可能是因为之前看到有人提按钮太小（这也是做主题的主要原因）所以刻意调大
当时闷头写，写完整个人都恍惚了
下次更新稍微调小一点，现在回看确实有点大
同时也会看着处理一下youtube主题下的巨大黑边

**Comment by esterTion** [comment]
已更新1.3.0.1
