### ISSUE TITLE
扩展在chrome应用商店怎么被删除了？

### ISSUE THREAD

**Issue by GoogleGFW** [esterTion/Youku-HTML5-Player#84]
![qq 20170909222231](https://user-images.githubusercontent.com/26985927/30240976-67232010-95ad-11e7-9174-61d581520fa0.png)

同步失败准备去商店重新下载的，结果就没结果了。。。。

**Comment by esterTion** [comment]
审核让我添加隐私声明，加的时候第一次写错了，取消重新提交就卡在draft了
用首页的crx

**Comment by GoogleGFW** [comment]
了解。

**Comment by esterTion** [comment]
开开放着

**Comment by androidcn** [comment]
1.3.0.2
http://v.youku.com/v_show/id_XMzAxNjg5MzMyMA==.html?spm=a2h0z.8244218.2371631.3&debug=flv
在这里 

`Playback error
{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}`

**Comment by esterTion** [comment]
@androidcn 扩展冲突或网络问题

**Comment by ayanamist** [comment]
是否考虑在 https://greasyfork.org/ 上提供UserScript版本？

**Comment by esterTion** [comment]
@ayanamist 
新问题请开新issue
不考虑，没有跨域权限
