### ISSUE TITLE
支持greasyfork.org

### ISSUE THREAD

**Issue by ayanamist** [esterTion/Youku-HTML5-Player#86]
#84 的问题，可以通过脚本改成userscript的方式来解决

跨域的问题，有`GM_xmlhttpRequest`这个函数来解决 https://stackoverflow.com/a/11275659/522024

这种修改网页状态的脚本，根据以往经验，很容易被Chrome Web Store给下线

**Comment by esterTion** [comment]
视频流使用的是fetch流式获取，不支持GM_xhr

**Comment by esterTion** [comment]
并且，这个扩展没有任何扩展政策明令禁止的行为，这次出问题是chrome要求添加隐私声明，我编辑的时候取消了一次然后卡状态了
简单讲就是google后端逻辑感人

**Comment by ayanamist** [comment]
因为改YouTube的若干扩展都阵亡了……

**Comment by esterTion** [comment]
这就很没有道理了
扩展本质意义就是修改网页状态，按你这种讲adblock都该被下架

**Comment by ayanamist** [comment]
例如这个 https://github.com/YePpHa/YouTubeCenter/wiki#chrome--opera-15-extension

> taken down by Google, currently being reviewed

**Comment by fireattack** [comment]
@ayanamist 你要知道Google对自家的网站是有隐性双标的
