### ISSUE TITLE
商店不是已经恢复了吗？

### ISSUE THREAD

**Issue by zhanxiage233** [esterTion/Youku-HTML5-Player#89]
为啥又出来一个临时解决方案

**Comment by esterTion** [comment]
下午刚恢复的

**Comment by esterTion** [comment]
我刚刚看了眼才发现恢复了，目前正常上架但后台还是没完全恢复

**Comment by zhanxiage233** [comment]
@esterTion  上午10点多就恢复了，可以正常更新到最新版本 使用也没问题啊 
后台没完全恢复的意思是你暂时不能继续更新？

**Comment by esterTion** [comment]
上午恢复了？？？
我是完全不知道，刚才看到去给开发者反馈发邮件说明，目前后台上没有编辑按钮。不过我平时都是api更新，那边应该没问题，可能就是无法改简介

**Comment by zhanxiage233** [comment]
@esterTion 没问题就好，很棒的扩展！
