### ISSUE TITLE
获取视频地址出错，详细错误： NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by w153140** [esterTion/Youku-HTML5-Player#9]
获取视频地址出错，详细错误：
NetworkError when attempting to fetch resource

火狐浏览器52版本1.0.11

**Comment by esterTion** [comment]
你是否使用了其他的例如adblock屏蔽了链接，测试52.0.2正常
获取地址是play.youku.com/play/get.json
![](https://estertion.win/wp-content/uploads/2017/05/cd0797d176a606e9e9ab809da08b786f03d3bfe7.jpg)
