### ISSUE TITLE
优酷的 HTML5 播放器太难用了，能加入屏蔽官方播放器功能么？

### ISSUE THREAD

**Issue by xiaopangmd** [esterTion/Youku-HTML5-Player#92]
我用 macOS 10.12.6，打开优酷默认官方 HTML5 播放器，切回原版播放器之后还是官方 HTML5 播放器，有办法屏蔽官方播放器么？

**Comment by xqdoo00o** [comment]
优酷的h5切换规则改了，已经PR。

**Comment by LZJwrtj** [comment]
为什么今天这个插件在我的电脑上不能用了？昨天还可以，今天就一直启动不了一直是官方的

**Comment by esterTion** [comment]
已更新1.3.0.7
