### ISSUE TITLE
优酷每集看点，在播放进度条没有标记

### ISSUE THREAD

**Issue by lilingang162786** [esterTion/Youku-HTML5-Player#95]
比如水浒传http://v.youku.com/v_show/id_XMTExODU4OTky.html  每集都有3到4个看点标记

**Comment by esterTion** [comment]
不太想加到进度条上，影响操作而且写起来不方便…右键菜单怎么样

**Comment by lilingang162786** [comment]
这个无所谓哪里，最好能有，看老的电视剧想看哪里找起来方便

**Comment by esterTion** [comment]
已更新1.3.1.1
