### ISSUE TITLE
获取视频信息出错，详细错误： {"note":"客户端无权播放,201","code":-6004}

### ISSUE THREAD

**Issue by yaoyao5128** [esterTion/Youku-HTML5-Player#96]
版本1.3.0.7 多个外链视频显示  获取视频信息出错，详细错误： {"note":"客户端无权播放,201","code":-6004}    
例如：http://bbs.winning11cn.com/thread-1216239-1-2.html 
（清除浏览器缓存后会出现此问题，使用浏览器chrome）
（临时解决办法：访问一次优酷本站后故障消失）

![image](https://user-images.githubusercontent.com/31963173/30694676-9e4d345a-9f07-11e7-8d22-2c602511c890.png)

**Comment by esterTion** [comment]
已更新1.3.1.1
