### ISSUE TITLE
这两天发现一个问题，就是中途缓冲。

### ISSUE THREAD

**Issue by yuluo-ding** [esterTion/Youku-HTML5-Player#97]
在看视频的时候，中途会有很大概率出现缓冲界面，时间是0.02s和0.04s。浏览器是chrome最新版本。

**Comment by esterTion** [comment]
刚刚更新的版本已经加了低网速(50k)10秒自动重载

**Comment by yuluo-ding** [comment]
我用的就是 1.3.1.5的版本，我这两天再试试看呢。
