### ISSUE TITLE
firefox 58  nightly 无法全屏

### ISSUE THREAD

**Issue by GithubUsername3** [esterTion/Youku-HTML5-Player#98]
网页全屏正常，全屏会恢复原状

**Comment by esterTion** [comment]
还没看，但按你这个描述多半是浏览器bug

**Comment by GithubUsername3** [comment]
有另外一个问题，qq浏览器(chrome53)和firefox在播某些多音轨视频时，会2个音轨同时放，chrome 62正常。

http://v.youku.com/v_show/id_XMjI3MDE5Mjky.html?spm=a2h0j.8191423.vpofficiallistv5_wrap.5~5~5~5!2~A

**Comment by yfdyh000** [comment]
@GithubUsername3 Nightly 58，没听到同时播放。

**Comment by esterTion** [comment]
源问题
用flash也一样，不知道他们把国语源怎么了

**Comment by GithubUsername3** [comment]
源问题的话那就挺奇怪，chrome 62正常，qq和firefox暂停时，图像和音轨都停止，但另一音轨还在播放

**Comment by esterTion** [comment]
早上试的时候复现了，刚才并没有再出现
那应该是移除优酷播放器的时候他自己播放器开始播放了
简单讲大概就是……你电脑性能不够快没有及时移除旧播放器，刷新多次应该可破

**Comment by GithubUsername3** [comment]
嗯，证明2个事，yfdyh000和esterTion电脑性能比我好，chrome 62性能好

**Comment by esterTion** [comment]
我这边现在有点奇怪……好像是教育网学校搞的重定向把yk的hls播放搞崩了
我看看怎么解决

---
事实是chrome性能确实很好，firefox的js越来越卡了

**Comment by GithubUsername3** [comment]
也不对，我给的链接，firefox怎么刷新2个音轨都会播。但是首页的《反黑》是正常的，难道是这两个视频的页面，js占用电脑性能是不同导致的？

**Comment by esterTion** [comment]
试了几遍大概搞懂发生什么了
我现在的方法是，yk页面加载好之后，直接移除yk播放器
因为大部分现在都是默认html5了，所以我调用了`ykPlyr.remove()`
但是yk播放器逻辑写的有些问题，我这个调用太早了，然后在他hls内容加载好之后，就自动开始播放他加载的了，和我加载的就重复了

但是这个video我还找不到，因为已经不在页面上而只是存在在js里作为变量了

**Comment by esterTion** [comment]
全屏的我看了……emmmm，被优酷的代码退出全屏了
去他妈的，我要日他的script地址了

**Comment by GithubUsername3** [comment]
嗯，几个大型视频网站推出html5,优酷的毛病好像是最多的，什么跨域cdn，这个那个的太多了

**Comment by esterTion** [comment]
更新了1.3.1.6
用了一个比较暴力的方法（在他创建播放器函数的中间来个报错强制中断），但是可能不够可靠，毕竟换个函数就不起作用了
全屏问题同样解决了
