### ISSUE TITLE
Operation is not supported

### ISSUE THREAD

**Issue by ilisten** [esterTion/Youku-HTML5-Player#99]
ubuntu 17.04   firefox  52.0.1  64bit
播放报错，错误代码如下
```
播放错误
{
  "type": "MediaError",
  "info": "MediaMSEError",
  "detail": {
    "code": 9,
    "msg": "Operation is not supported"
  }
}
```

**Comment by esterTion** [comment]
持续出现还是视频特例，还是只出现一次

**Comment by basten1899** [comment]
偶尔播放会出现这个  而且是播放途中突出出现 加载失败 然后弹出错误

**Comment by esterTion** [comment]
怎么个偶尔法，同视频同时间点不能复现？
这种我也无法排错

**Comment by basten1899** [comment]
又出来了
播放错误
{
  "type": "MediaError",
  "info": "FormatUnsupported",
  "detail": {
    "code": -1,
    "msg": "Non-FLV, Unsupported media type"
  }
}

**Comment by esterTion** [comment]
是否必然发生？视频地址和发生时间是什么？

**Comment by basten1899** [comment]
不必然  刷新就好了

**Comment by esterTion** [comment]
发生频率多少，如果很低我推断是网络问题，我没法修

**Comment by basten1899** [comment]
看2集 大概会出现一次

**Comment by basten1899** [comment]
看完一集 点下一集的时候容易出现（win10 chrome 61 64bit）

**Comment by basten1899** [comment]
看个蒙面唱将  快进着看  居然报错3次 ， 看来 快进也容易出错

**Comment by ilisten** [comment]
目前已正常。
目前版本是 firefox 56.0 64位
